version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - '8080:80'
    volumes:
      - ./src/api:/var/www/html/src/api
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  frontend:
    build:
      context: ./src/app
      dockerfile: dockerfile
    container_name: frontend
    ports:
      - '3001:3000'
    volumes:
      - ./src/app:/var/www/html/src/app
    networks:
      - laravel



  db:
    image: mysql:8.0.33
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - '4406:4406'
    volumes:
      - ./mysql:/var/lib/mysql
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - laravel



  backend:
    build:
      context: ./src/api
      dockerfile: dockerfile
    container_name: backend
    volumes:
      - ./src/api:/var/www/html/src/api
      - /run/php:/run/php
    ports:
      - "9000:80"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge