FROM mysql:latest

# Copiar el archivo init_db.sql al directorio docker-entrypoint-initdb.d
COPY ./init_db.sql /docker-entrypoint-initdb.d/


# Puerto que expondrá el contenedor
EXPOSE 3306

# Comando que se ejecutará cuando el contenedor se inicie
CMD ["mysqld"]